package com.smate.web.group.jms.quene.model;

/**
 * 枚举.
 * 
 */
public enum SnsSyncGroupActionEnum {

  SYNC_GROUP_ADD, SYNC_GROUP_INVITE_PSN_ADD, SYNC_GROUP_DELETE, SYNC_GROUP_INVITE_PSN_DELETE, SYNC_GROUP_PSN_TO_INVITE_PSN, SYNC_FRIEND_TO_SEND_GROUP_PSN, SYNC_TO_RECEIVE_GROUP_PSN, SYNC_FRIEND_TO_SEND_GROUP_PSN_CHANGE, SYNC_GROUP_GUID, SYNC_GROUP_OWNER_CHANGE, SYNC_GROUP_VISIT_DATE
}
