var improveimpact ={
    impactTitle:'Here are some suggestions to help you increase the impact of you research',
    impactStep:'Suggestions:',
    confirmTitle:'Confirm Publication',
    confirmTip:'Confirm your publication and publish on your profile',
    viewMore:'View More',
    confirmYesBtn:'Confirm',
    confirmNoBtn:'Ignore',
    uploadTitle:'Upload FullText',
    uploadTip:'Confirm and upload your publication full-text to increase research exposure',
    uploadNoFulltextBtn:'No FullText',
    uploadFulltextBtn:'Upload',
    friendTitle:'Expand your network',
    friendTip:'Invite research peers to be your contacts and get their latest research',
    friendIgnoreBtn:'Ignore',
    friendAttentionBtn:'Add Follow',
    friendAddBtn:'Add Contact',
    groupTitle:'Join Group',
    groupTip:'Discuss research difficulties with research peers',
    groupCancelBtn:'Ignore',
    groupAddBtn:'Join Group',
    groupCategoryCur:'Course Group',
    groupCategoryPro:'Project Group',
    groupCategoryInterest:'Interest',
    groupMember:'Members',
    groupRef:'References',
    groupPub:'Publications',
    groupCourse:'Courseware',
    groupFile:'Files',
    groupWork:'Assignments',
    psnTile:'Share personal information',
    psnTip:'Add your research profile hyperlink to other websites',
    psnClose:'Added',
    psnShare:'Share link',
    psnContent:'Add your research profile hyperlink to other websites to get 5 times higher publication browse',
    inviteFriend:'Send friend invitation to my co-authors'
}