var pubi18n ={
		i18n_timeout:'系统超时或未登录，你要登录吗？',
		i18n_tipTitle:'提示',
		i18n_like:'赞',
		i18n_share:"分享",
		i18n_unlike:"取消赞",
		i18n_optSuccess:"操作成功",
		i18n_uploadSuccess:"上传成功",
		i18n_onPermissions:"权限不足",
		i18n_delete_content:"你确定要删除选中的成果吗？",
		i18n_pub_share_content:"当前成果隐私设置为仅本人查看，请先将此成果隐私设置为公开",
		i18n_delete_title:"提示",
		i18n_delete_pub1:"成功删除",
		i18n_delete_pub2:"条成果",
		i18n_delete_pub:"删除成果",
		i18n_send_success:"联系人请求发送成功",
		i18n_addself:"自己不能添加自己为联系人",
		i18n_recentOneYear: " 年以来",
		i18n_recentThreeYear: " 年以来",
		i18n_recentFiveYear: " 年以来",
		i18n_shareSuccess:"分享成功",
		i18n_shareFail:"分享失败",
		i18n_pubIsDeleted:"成果已被删除",
		i18n_collectionSuccess:"收藏成功",
		i18n_collectionFail:"收藏失败",
		i18n_delSuccess:"删除成功",
		i18n_delFail:"删除失败",
		i18n_delete_pub_error:"删除成果出错",
		i18n_pubIsSaved:"已收藏该成果",
		i18n_pubImportError:"操作失败",
		i18n_pubnotExist1:"有",
		i18n_pubnotExist2:" 条成果数据异常，无法导入",
		i18n_pubnoselect:"请至少选择一条记录",
		i18n_optSuccess : '成果导入成功',
		i18n_optFailed : '成果导入失败',
		i18n_choose_confirm_btn : "确定",
    i18n_choose_cancel_btn : "取消",
		i18n_confirmDup : "该成果已加入你的成果库中",
		i18n_pub_not_owener_share_content:"当前成果隐私设置为仅本人查看，无法分享",
		i18n_choose_close_btn : "关闭",
		i18n_req_success: '发送全文请求成功',
    i18n_req_error: '请求发送失败，系统异常，请稍后再试'
}