var pubi18n ={
		i18n_timeout:'You are not logged in or session time out, please log in again',
		i18n_tipTitle:'Reminder',
		i18n_like:'Like',
		i18n_share:'Share',
		i18n_unlike:'Unlike',
		i18n_optSuccess:'Operated successfully',
		i18n_uploadSuccess:'Uploaded successfully',
		i18n_onPermissions:"No permission to perform this operation",
		i18n_delete_content:"Are you sure to delete the selected publication(s)?",
    i18n_pub_share_content:'The publication is set to private, please set to "open to public" first',
		i18n_delete_title:"Reminder",
		i18n_delete_pub1:"",
		i18n_delete_pub2:"Publication Deleted",
		i18n_delete_pub:"Publication Deleted",
		i18n_send_success:"Request sent",
		i18n_addself:"You are not allowed to add yourself as contact",
		i18n_recentOneYear: "Since ",
		i18n_recentThreeYear: "Since ",
		i18n_recentFiveYear: "Since ",
		i18n_shareSuccess:"Shared successfully",
		i18n_shareFail:"Shared failed",
		i18n_pubIsDeleted:"The publication has been deleted",
		i18n_collectionSuccess:"Saved successfully",
		i18n_collectionFail:"Saved failed",
		i18n_delSuccess:"Delete successfully",
		i18n_delFail:"Delete failed",
		i18n_delete_pub_error:"删除成果出错",
		i18n_pubIsSaved:"The publication has been saved",
		i18n_pubImportError:"Operated failed",
		i18n_pubnotExist1:"",
		i18n_pubnotExist2:" publications import failed, please try again later",
		i18n_pubnoselect:"Please select at least one record",
		i18n_confirmDup : "The publication is already imported",
		i18n_optSuccess : 'Operated successfully',
		i18n_choose_confirm_btn : "Confirm",
		i18n_choose_cancel_btn : "Cancel",
		i18n_optSuccess : 'Operated successfully',
		i18n_optFailed : 'Operated failed',
		i18n_pub_not_owener_share_content:"The publication is set to private, and cannot be shared",
		i18n_choose_close_btn : "Close",
		i18n_req_success: 'Request has been sent successfully',
		i18n_req_error: 'Request failed, please try again later'
}