/**
 * dynamic.common.js,dynamic.pc.detail.js共用国际化
*/
var Pubsearch={
		like:'赞',
		unlike:'取消赞',
		share:'分享',
		shareSuccess:'分享成功',
		shareFail:'分享失败，请稍候再试',
		cmtListError:'获取评论列表异常',
		noMoreRecord:"没有更多记录",
		noRecord:"未找到符合条件的记录",
		addFail:'添加失败，请稍候再试',
		addEmptyArea:'输入的科技领域不能为空',
		addEmptyKey:'输入的关键词不能为空',
		addAreaSizeFail:'最多5个科技领域',
		addKeySizeFail:'最多10个关键词',
		addAreaRepFail:'已有该科技领域',
		addKeyRepFail:'已有该关键词',
		deleteFail:'删除失败，请稍候再试',
		pubIsSaved:'已收藏该成果',
		saveSuccess:'收藏成功',
		saveFail:'收藏失败',
		noPub:'成果不存在',
		dowload:'下载',
		optSuccess:"操作成功",
		optFailed: '操作失败',
		save:"收藏",
		unsave:"取消收藏",
};