var homepage = {
  "systemBusy" : "System busy！Try agin later",
  "shortAddressNote" : "Short-url should have no more than 20 characters and contain only 'A-Za-z0-9_'",
  "operateSuccess" : "Operated successfully",
  "trueEmail" : "Please enter a valid e-mail address",
  "truePhone" : "Please enter a valid phone number",
  "trueStartTime" : "Please choose a valid start year",
  "trueEndTime" : "Please choose a valid end year",
  "inputInsName" : "Institution name is required",
  "copySuccess" : "Copied successfully",
  "timeOut" : "You are not logged in or session time out, please log in again",
  "addFriendRequest" : "Request sent",
  "tips" : "Reminder",
  "notPrjTitle" : "Project title must not be empty",
  "notPrjAbstract" : "Project abstract must not be empty",
  "notPrjPrivacy" : "Group privacy must be chosen",
  "notPrjResearchArea" : "Areas must not be empty",
  "addFriend" : "Request sent",
  "firstNameEmpty" : "First name must not be empty",
  "lastNameEmpty" : "Last name must not be empty",
  "keyWordRepeat" : "Keywords must not repeat",
  "fail" : "fail",
  "scienceAreaNotNull" : "Areas should not be empty",
  "scienceAreaLimit" : "MaxiMun enter up to 5 areas only",
  "keywordsNotNull" : "Keywords must not be empty",
  "unit" : "k",
  "otherAgency" : "Other",
  "noRecord" : "No matched record has been found",
  "repeatpubdel" : "Deleted",
  "repeatpubkeep" : "Saved",
  "noteCVname" : "输入简历名称",
  "repeatPubAllSave" : "Save all publications in this group",
  "repeatPubNextRecord" : "Next Group",
  "repeatPubLastRecord" : "Previous Group",
  "repeatPubAutoToRecord" : "Jump to the next group soon",
  "attentionPsn" : "Follow successfully",
  "attentionPsnFail" : "Follow failed",
  "cancelAttentionPsn" : "Unfollow successfully",
  "cancelAttentionPsnFail" : "Unfollow failed",
  "cancelFriend" : "UnContact successfully",
  "cancelFriendFail" : "UnContact failed",
  "cancelAttention" : "Unfollow",
  "addAttention" : "Follow",
  "sureCancelFriend" : "Are you sure to remove this Contact？",
  "sure": "Confirm",
  "cancel": "Cancel"
}