var homepage = {
  "systemBusy" : "系统繁忙",
  "shortAddressNote" : "短地址由不超过20个字符的字母、数字和下划线组成",
  "operateSuccess" : "操作成功",
  "trueEmail" : "请填写正确的邮箱",
  "truePhone" : "请填写正确的电话号码",
  "trueStartTime" : "请填写正确的开始时间",
  "trueEndTime" : "请填写正确的结束时间",
  "inputInsName" : "请填写机构名称",
  "copySuccess" : "已复制好，可贴粘",
  "timeOut" : "系统超时或未登录，你要登录吗？",
  "addFriendRequest" : "联系人请求发送成功",
  "tips" : "提示",
  "notPrjTitle" : "项目标题不能为空",
  "notPrjAbstract" : "项目摘要不能为空",
  "notPrjPrivacy" : "权限不能为空",
  "notPrjResearchArea" : "科技领域不能为空",
  "addFriend" : "联系人请求发送成功",
  "firstNameEmpty" : "First name不能为空",
  "lastNameEmpty" : "Last name不能为空",
  "keyWordRepeat" : "关键词不能重复",
  "fail" : "操作失败",
  "scienceAreaNotNull" : "请选择一个科技领域",
  "scienceAreaLimit" : "最多选择5个科技领域",
  "keywordsNotNull" : "请输入一个关键词",
  "unit" : "万",
  "otherAgency" : "其他",
  "noRecord" : "未找到符合条件的记录",
  "repeatpubdel" : "已删除",
  "repeatpubkeep" : "已保留",
  "noteCVname" : "输入简历名称",
  "repeatPubAllSave" : "保留本组全部成果",
  "repeatPubNextRecord" : "下一组",
  "repeatPubLastRecord" : "上一组",
  "repeatPubAutoToRecord" : "即将跳转下一组",
  "attentionPsn" : "关注成功",
  "attentionPsnFail" : "关注失败",
  "cancelAttentionPsn" : "取消关注成功",
  "cancelAttentionPsnFail" : "取消关注失败",
  "cancelFriend" : "删除联系人成功",
  "cancelFriendFail" : "删除联系人失败",
  "cancelAttention" : "取消关注",
  "addAttention" : "关注",
  "sureCancelFriend" : "确定删除该联系人吗？",
  "sure": "确定",
  "cancel": "取消"

}