var Enter={
		applicationNo: "申请号:",
		patentNo: "专利号:",
		publicNo: "公开号:",
		partenApplicationDate: "申请日期:",
		partenPublicDate: "公开日期:",
		patentee: "专利权人:",
		applier: "申请人:",
		maxAccessy: "最多添加10个附件",	
		notMenberName: "请先输入作者姓名",
		acceptDate: "接收日期:",
		publishDate: "发表日期:",	
		firstRegion:"选择一级地区",
		secondRegion:"选择二级地区",
		thirdRegion:"选择三级地区",
		pubIsDeleted:"成果已被删除",
		scienceAreaLimit : "最多选择2个科技领域",
		pubIsNotExist : "成果不存在",
		error:"保存成果失败",
		public:"所有人都可以查看",
    onlyMe:"仅自己可以查看",
    saveOk:"保存成功",
    saveIncomplete:"保存成功，但你的数据尚未填写完整",
    notEmpty:"不能为空",
    backlist:"返回列表",
    continue:"继续编辑",
    journalName:"期刊名不能为空",
    ISSNFormat:"ISSN格式不正确",
    keyWordRepeat:"关键词重复",
    journalNameTips:"期刊名最大长度为250",
    keywordsLimit:"关键词数量已超过最大个数",
    privatePubfulltextTips:"隐私成果的全文无法公开",
    reupload:"重新上传",
    changeType_confirm:"是",
    changeType_cancel:"否",
    reupload:"重新上传",
    tips:"提示",
    confirm_btn:"不公开",
    cancel_btn:"公开",
    private_content:"公开的论文成果有助于提高科研影响力，是否保持公开？",
    standard_international:"国际标准",
    standard_nation_force:"国家标准（强制）",
    standard_nation_recommended:"国家标准（推荐）",
    standard_industrial_force:"行业标准（强制）",
    standard_industrial_recommended:"行业标准（推荐）",
    standard_local:"地方标准",
    standard_enterprise:"公司标准",
    standard_other:"其他标准"
}


