var Enter={
		applicationNo: "Application No:",
		patentNo: "Patent No:",		
		publicNo: "Publication Number:",
		partenApplicationDate: "Application Date:",
		partenPublicDate: "Publication Date:",
		patentee: "Patentee:",
		applier: "Applicant:",
		maxAccessy: "Maximum add 10 attachments",			
		notMenberName: "Please enter the author",	
		acceptDate: "Acceptance Date",
		publishDate: "Publication Date:",
		firstRegion:"Country",
		secondRegion:"Region/Province",
		thirdRegion:"City",
		pubIsDeleted:"The publication has been deleted",
		scienceAreaLimit:"MaxiMun enter up to 2 areas only",
		pubIsNotExist : "The publication is not exist",
		error:"error",
		public:"Public",
    onlyMe:"Only Me",
    saveOk:"Saved successfully",
    saveIncomplete:"Saved successfully,But your data is incomplete",
    notEmpty:" should not be empty",
    backlist:"Back",
    continue:"Continue",
    journalName:"Journal Name should not be empty",
    ISSNFormat:"ISSN is incorrect",
    keyWordRepeat:"Keywords must not repeat",
    journalNameTips:"Journal name is limited to 250 characters",
    keywordsLimit:"MaxiMun enter up to 5 keywords only",
    privatePubfulltextTips:"The fulltext of private publication cannot be opened",
    reupload:"Upload",
    changeType_confirm:"Yes",
    changeType_cancel:"No",
    reupload:"Upload",
    tips:"Reminder",
    confirm_btn:"Not Now",
    cancel_btn:"Open",
    private_content:"Open your publication to the public and improve research impact",
    standard_international:"International Standard",
    standard_nation_force:"National Standard(Compulsory)",
    standard_nation_recommended:"National Standard(Recommendatory)",
    standard_industrial_force:"Industry Standard(Compulsory)",
    standard_industrial_recommended:"Industry Standard(Recommendatory)",
    standard_local:"Local Standard",
    standard_enterprise:"Company Standard",
    standard_other:"Other Standard"
    
}
