var groupDetailFiles = {
  selectFoler : "请选择文件夹",
  prompt : "提示",
  noRemove : "对不起，你不能移除他人加入群组的文件",
  noRemoveToFolder : "对不起，你不能移动他人加入群组的文件",
  selectFile : "请选择文件",
  comfirm : "你确定将选定文件移除该文件夹？",
  deleteComfirm : "你确定将选定文件移除该群组？",
  noComment : "不能对多个文件同时进行评论",
  selectUploadFile : "选择你要上传的文件",
  selectEdit : "请选择其中的一项进行修改编辑",
  fileMaxSize : "文件描述不能超过200字符",
  noUpdate : "对不起，你无权修改此文件",
  opSuccess : "操作成功",
  opFaild : "操作失败",
  noRating : "暂无评分",
  all : "共",
  comment : "人评论，",
  rate : "评分.<br/>",
  loginTime : "系统超时，请重新登录",
  recommendLabel : "评论"
};
